sonar.projectKey=alexlittle-github_django-photo
sonar.organization=alexlittle-github
sonar.projectName=django-photo

sonar.sources=.
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# exclusions
sonar.exclusions=tests/**,docs/**,**/bootstrap-*-dist/**,**/migrations/**,**/*.js
sonar.coverage.exclusions=**/settings*.py,manage.py