# Generated by Django 2.1.5 on 2019-02-09 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import photo.fields
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', photo.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from='name', unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('date_display', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('slug', photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='file', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('album_cover', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
            options={
                'verbose_name': 'Photo property',
                'verbose_name_plural': 'Photo properties',
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
            options={
                'verbose_name': 'Photo Tag',
                'verbose_name_plural': 'Photo Tags',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag Category',
                'verbose_name_plural': 'Tag Categories',
            },
        ),
        migrations.CreateModel(
            name='TagProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Tag')),
            ],
            options={
                'verbose_name': 'Tag property',
                'verbose_name_plural': 'Tag properties',
            },
        ),
        migrations.CreateModel(
            name='ThumbnailCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=photo.models.image_file_name)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
            options={
                'verbose_name': 'Thumbnail Cache',
                'verbose_name_plural': 'Thumbnail Caches',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='tagcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.TagCategory'),
        ),
        migrations.AddField(
            model_name='phototag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(through='photo.PhotoTag', to='photo.Tag'),
        ),
    ]
