# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 21:02
from __future__ import unicode_literals

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_squashed_0010_auto_20171120_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from=b'name', unique=True),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='slug',
            field=photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from=b'name', unique=True),
        ),
    ]
