# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
