# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 21:21
from __future__ import unicode_literals

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180302_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=photo.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True, populate_from=b'name', unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=photo.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from=b'file', unique=True),
        ),
    ]
