# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180302_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(through='photo.PhotoTag', to='photo.Tag'),
        ),
    ]
