# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20171119_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='location',
            new_name='album',
        ),
    ]
