# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
            options={
                'verbose_name': 'Photo property',
                'verbose_name_plural': 'Photo properties',
            },
        ),
    ]
