# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photoprops'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Tag')),
            ],
            options={
                'verbose_name': 'Tag property',
                'verbose_name_plural': 'Tag properties',
            },
        ),
    ]
