# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=b'thumbcache/%Y/%m/%d')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Photo')),
            ],
        ),
    ]
