# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import photo.cache_storage


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_thumbnailcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_file', models.ImageField(storage=photo.cache_storage.ImageCacheFileSystemStorage(), upload_to=photo.cache_storage.media_file_name)),
                ('md5sum', models.CharField(max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='thumbnailcache',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=photo.cache_storage.ImageCacheFileSystemStorage, upload_to=b'cache'),
        ),
    ]
