# Generated by Django 4.2 on 2023-04-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
