# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_tagprops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
