# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20171120_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailcache',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=photo.models.image_file_name),
        ),
    ]
