# Generated by Django 4.2 on 2023-04-23 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0007_remove_album_slug_remove_photo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagcategory",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
