# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20180310_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_display',
            field=models.TextField(blank=True, null=True),
        ),
    ]
