# Generated by Django 5.1.1 on 2024-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprops',
            name='value',
            field=models.TextField(),
        ),
    ]
