# Generated by Django 5.1.8 on 2025-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_fulltext_indices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThumbnailCache',
        ),
    ]
