# Generated by Django 6.0.7 on 2026-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0012_combinedsearch_delete_thumbnailcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="photo",
            name="md5hash",
        ),
        migrations.AddField(
            model_name="photo",
            name="file_hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
