# Generated by Django 6.0.7 on 2026-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0013_combinedsearch_remove_photo_md5hash_photo_file_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
