# Generated by Django 6.0.7 on 2026-08-27 18:38

from django.db import migrations


def dedupe_phototags(apps, schema_editor):
    """Keep the earliest PhotoTag row for each (photo, tag) pair, drop the rest.

    Needed before the unique_together below can be applied -- clean_combine_tags
    used to create duplicate rows via pt.save() instead of get_or_create.
    """
    PhotoTag = apps.get_model("photo", "PhotoTag")
    seen = set()
    for phototag in PhotoTag.objects.order_by("id").only("id", "photo_id", "tag_id"):
        key = (phototag.photo_id, phototag.tag_id)
        if key in seen:
            phototag.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0014_alter_photo_file_hash"),
    ]

    operations = [
        migrations.RunPython(dedupe_phototags, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="phototag",
            unique_together={("photo", "tag")},
        ),
    ]
