# Generated by Django 6.0.7 on 2026-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0015_phototag_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="date_display",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="file_hash",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
    ]
